### ISSUE TITLE
Do not use zero= English strings

### ISSUE THREAD

**Issue by Nikerabbit** [Ajapaik/Android-app#3]
Message [profile rephotos](https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=strings-profile_rephotos&group=ajapaik-app&language=fi&filter=&optional=1&action=translate) uses `zero` key in English to mean 0. In some languages the zero key does not mean (only) 0 though, see for example Latvian in https://www.unicode.org/cldr/charts/34/supplemental/language_plural_rules.html

A separate string should be used for the case of real 0.

**Comment by MaertHaekkinen** [comment]
Hi, thank you for the feedback.

I have made a commit regarding the issue. If you have time, please feel free to check it out, if it was you had in mind.
https://github.com/Ajapaik/ajapaik-android-app/commit/5e77c946ca3fdad969bb2db544e1e599eb2dfb39

**Comment by Nikerabbit** [comment]
Yes I saw this during imports. Looks good.
